  - name: Creates directory
    `  file:
         path: ~/backend
         state: directory
  - name: Copy backend artifacts
    template:
     src: "files/index.js"
     dest: "~/web/index.js"

  - name: Copy backend artifacts
    tasks:
      - name: Copying the Directory's contents (sub directories/files)
        become: true
        copy:
          src: ~/Downloads/logos/
          dest: ~/backend
  - name: Executing node
   shell: |
     node backend/main.js