  - name: Copy backend artifacts
    become: true
    copy:
      src: /root/project/backend
      dest: /home/ubuntu/

  - name: Executing node
    shell: |
      cd /home/ubuntu/backend
      npm run start:prod