  - name: Copy backend artifacts
    become: true
    copy:
      src: /root/project/backend/dist
      dest: /home/ubuntu/

  - name: Executing node
    shell: |
      cd /home/ubuntu/dist
      node main.js