  - name: "copy dist archive"
    copy:
      src: ../../backend.tar.gz
      dest: backend.tar.gz

  - name: "Unpack dist archive"
    shell: |
      tar -xzf backend.tar.gz
      rm backend.tar.gz

  - name: Install dependencies
    shell: |
      cd /home/ubuntu/backend
      npm i

  - name: Configure env
    shell: |
      cd /home/ubuntu/backend
      touch .env
      echo "ENVIRONMENT=production" >> backend/.env
      echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> backend/.env
      echo "TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> backend/.env
      echo "TYPEORM_HOST=${TYPEORM_HOST}" >> backend/.env
      echo "TYPEORM_PORT=${TYPEORM_PORT}" >> backend/.env
      echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> backend/.env
      echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> backend/.env
      echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> backend/.env

  - name: Executing node
    shell: |
      cd /home/ubuntu/backend
      node dist/main.js