  - name: "copy dist archive"
    copy:
      src: ../../backend.tar.gz
      dest: backend.tar.gz

  - name: "Unpack dist archive"
    shell: |
      tar -xzf backend.tar.gz
      rm backend.tar.gz

  - name: Executing node
    shell: |
      cd /home/ubuntu/backend
      ls -lh
      npm run start:prod