  - name: Creates directory
    file:
      path: ~/backend
      state: directory

  - name: Copy backend artifacts
    become: true
    copy:
      src: ~/backend/dist/
      dest: ~/backend

  - name: Executing node
    shell: |
      node ~/backend/main.js