global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093


scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key: XXXX
        secret_key: XXXX
        port: 9100
        filters:
          - name: tag:project
            values:
              - udapeople
